CREATE TABLE CLIENTS (
  CLIENT_ID mediumint unsigned NOT NULL AUTO_INCREMENT,
  EMAIL varchar(175) DEFAULT NULL,
  NAME varchar(250) DEFAULT NULL,

  PRIMARY KEY (CLIENT_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DEVS (
  DEV_ID varchar(50) NOT NULL,
  CLIENT_ID mediumint unsigned DEFAULT NULL,
  DEV_TYPE varchar(50) DEFAULT NULL,

  PRIMARY KEY (DEV_ID),
  CONSTRAINT DEVS_fk_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
